#!/bin/tcsh
# EPICS startup script for caQtDM
#
# Put the autoconvert directory last in the path
setenv CAQTDM_DISPLAY_PATH LabJackApp/op/ui/autoconvert

# Launch caQtDM
caQtDM -noMsg LabJackTop.ui &

