TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

# Note, the following files were manually copied from the LabJack LJM distribution
INC += LabJackM.h

LIB_INSTALLS_WIN32 += ../os/windows-x64/LabJackM.lib
LIB_INSTALLS_Linux += ../os/linux-x64/libLabJackM.so

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

