TOP = ../..
include $(TOP)/configure/CONFIG

# Note: do a "make clean" before switching platforms.
#       then comment/uncomment as follows:

ARCH = $(EPICS_HOST_ARCH)
TARGETS = envPaths

include $(TOP)/configure/RULES.ioc
