TOP = ../..
include $(TOP)/configure/CONFIG

# Note: do a "make clean" before switching platforms.
#       then comment/uncomment as follows:

# For Linux ioc
ARCH = linux-x86_64
TARGETS = envPaths

# For vxWorks ioc
#ARCH = vxWorks-ppc32
#TARGETS = cdCommands

include $(TOP)/configure/RULES.ioc
