name: Publish Sphinx Docs to GitHub Pages
on: [push]

# see: https://sphinx-notes.github.io/pages/
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

jobs:

  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Install pip
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python3-pip
        which pip3
        which pip

    - name: Install furo theme
      run: |
        pip install furo "pygments >=2.7.0"

    - name: Install package
      run: |
        pip install --no-deps -e .
        which LabJack

    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        # path to conf.py directory
        documentation_path: docs/source

    - name: Push changes if refs/tags
      if: startsWith(github.ref, 'refs/tags')
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages